name: 'Taplo'
description: 'GitHub Action to run Taplo. Taplo is TOML formatter and linter'
author: 'hituzi no sippo'
inputs:
  token:
    description: 'The GITHUB_SECRET token'
    required: true
  args:
    description: 'CLI Arguments to pass to Taplo'
    required: true
  version:
    description: 'The version of Taplo to run'
runs:
  using: 'node16'
  main: 'dist/index.js'
